version: '2.1'

services:

  forest-ds:
    build: .
    image: shsolutions/forest-ds:latest
    ports:
      - "8766:8766"
      - "27015:27015"
      - "27016:27016"
    environment:
      RACK_ENV: development
      SHOW: 'true'
      SESSION_SECRET:
    volumes:
      - "/home/steam/steamcmd"
      - "/home/steam/games"
#    networks:
#      app_net:
#        ipv4_address: 172.18.0.2

#networks:
#  app_net:
#    external: true
